<a href="https://colab.research.google.com/github/gdrag0n/Information-Retrieval/blob/main/TDIM%20Model%20Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [251]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [252]:
!ls
%cd MyDrive
!ls
%cd 'IR ASSIGNMENT'

'An Operating System1.txt'
'Modern Operating Systems.txt'
'Operating System a Case Study.txt'
'Operating Systems From 0 to 1.txt.txt'
'Operating Systems.txt'
'Operating System.txt'
'OS overview.txt'
'Research Journal of Recent Sciences.txt'
'TIBCO iProcess.txt'
'Topic- Operating Systems.txt'
'USGS Precipitation-Runoff Modeling System.txt'
[Errno 2] No such file or directory: 'MyDrive'
/content/drive/MyDrive/IR ASSIGNMENT
'An Operating System1.txt'
'Modern Operating Systems.txt'
'Operating System a Case Study.txt'
'Operating Systems From 0 to 1.txt.txt'
'Operating Systems.txt'
'Operating System.txt'
'OS overview.txt'
'Research Journal of Recent Sciences.txt'
'TIBCO iProcess.txt'
'Topic- Operating Systems.txt'
'USGS Precipitation-Runoff Modeling System.txt'
[Errno 2] No such file or directory: 'IR ASSIGNMENT'
/content/drive/MyDrive/IR ASSIGNMENT


### The OS module in Python provides functions for interacting with the operating system. 

In [257]:
# Import Module
import os
os.listdir()

['Operating System a Case Study.txt',
 'Operating System.txt',
 'Operating Systems From 0 to 1.txt.txt',
 'OS overview.txt',
 'USGS Precipitation-Runoff Modeling System.txt',
 'TIBCO iProcess.txt',
 'Research Journal of Recent Sciences.txt',
 'Modern Operating Systems.txt',
 'Operating Systems.txt',
 'Topic- Operating Systems.txt',
 'An Operating System1.txt']

# Part 1
### Searching for keyword in each file, returning all files the keyword is present in.

We are present in the directory required for the operations, hence no need to define a path.

* Step: Defining a function to search for 'keyword' through all the files in the directory


* Purpose: Return the list of the files 'keyword' is present in.

In [258]:
def search(keyword):
  l=[]
  for file in os.listdir():
    f= open(file, 'r')
    for x in f:                 #x: each line in f
      if keyword in x:          #if keyword in a line
        l.append(file)
        break

  if len(l)==0:
    return "Keyword not found"
  else:
    return l

### Running the queries:
* process
* operating
* cpu
* deadlock

Query 1:

In [259]:
search("process")

['Operating System a Case Study.txt',
 'Operating System.txt',
 'Operating Systems From 0 to 1.txt.txt',
 'OS overview.txt',
 'TIBCO iProcess.txt',
 'Research Journal of Recent Sciences.txt',
 'Modern Operating Systems.txt',
 'Operating Systems.txt',
 'An Operating System1.txt']

Query 2:

In [ ]:
search("operating")

['Operating System a Case Study.txt',
 'Operating System.txt',
 'Operating Systems From 0 to 1.txt.txt',
 'OS overview.txt',
 'USGS Precipitation-Runoff Modeling System.txt',
 'TIBCO iProcess.txt',
 'Research Journal of Recent Sciences.txt',
 'Operating Systems.txt',
 'Topic- Operating Systems.txt',
 'An Operating System1.txt']

Query 3:

In [ ]:
search("cpu")

['Operating System.txt', 'Operating Systems From 0 to 1.txt.txt']

Query 4:

In [ ]:
search("deadlock")

['Operating System a Case Study.txt',
 'Operating System.txt',
 'Research Journal of Recent Sciences.txt',
 'Modern Operating Systems.txt',
 'Operating Systems.txt']

# Part 2
Using the above, instead of appending the file name onto the list, creating an array with binary array which returns 1 when keyword is found and 0 when it is not.

In [260]:
def search(keyword):
  arr=[]
  for file in os.listdir():
    f= open(file, 'r')
    y=f.read()

    if keyword in y:
      arr.append(1)
    else:
      arr.append(0)

  return arr

Testing the queries again.

* Query 1:

In [ ]:
search("process")

[1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1]

* Query 2:

In [ ]:
search("operating")

[1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1]

* Query 3:

In [ ]:
search("cpu")

[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]

* Query 4:

In [ ]:
search("deadlock")

[1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0]

* Query 5:

In [ ]:
search("computer")

[1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1]

# Part 3
### Table Creation using pandas and numpy

importing numpy and pandas

In [261]:
import numpy as np
import pandas as pd

Modifying the code to suit the new format.

Incorporating dictionary.

In [262]:
def search(keyword):
  d={}
  for file in os.listdir():
    f= open(file, 'r')
    y=f.read()

    if keyword in y:
      r=1
      d[file]=r
    else:
      r=0
      d[file]=r
  
  return d

In [263]:
search("process")

{'Operating System a Case Study.txt': 1,
 'Operating System.txt': 1,
 'Operating Systems From 0 to 1.txt.txt': 1,
 'OS overview.txt': 1,
 'USGS Precipitation-Runoff Modeling System.txt': 0,
 'TIBCO iProcess.txt': 1,
 'Research Journal of Recent Sciences.txt': 1,
 'Modern Operating Systems.txt': 1,
 'Operating Systems.txt': 1,
 'Topic- Operating Systems.txt': 0,
 'An Operating System1.txt': 1}

Shows that the code is functioning as expected and as designed to.

Modifying the code so as to obtain a table for each query.

In [264]:
def search(keyword):
  d={}
  for file in os.listdir():
    f= open(file, 'r')
    y=f.read()

    if keyword in y:
      r=1
      d[file]=r
    else:
      r=0
      d[file]=r
      
  k=[keyword]
  df=pd.DataFrame(data=d, index=k)
  return df

In [265]:
search("process")

Operating System a Case Study.txt  Operating System.txt  \
process                                  1                     1   

         Operating Systems From 0 to 1.txt.txt  OS overview.txt  \
process                                      1                1   

         USGS Precipitation-Runoff Modeling System.txt  TIBCO iProcess.txt  \
process                                              0                   1   

         Research Journal of Recent Sciences.txt  \
process                                        1   

         Modern Operating Systems.txt  Operating Systems.txt  \
process                             1                      1   

         Topic- Operating Systems.txt  An Operating System1.txt  
process                             0                         1

In [266]:
keywords=["process", "cpu", "operating", "deadlock", "computer"]

t=[]
for i in keywords:
  d=search(i)
  t.append(d)

### Binary Sparse Matrix for TDIM Model

Table contains binary result for each query in the keyword list

In [267]:
df=pd.concat(t)
keyword=pd.Index(keywords)
df.set_index(keyword)

Operating System a Case Study.txt  Operating System.txt  \
process                                    1                     1   
cpu                                        0                     1   
operating                                  1                     1   
deadlock                                   1                     1   
computer                                   1                     1   

           Operating Systems From 0 to 1.txt.txt  OS overview.txt  \
process                                        1                1   
cpu                                            1                0   
operating                                      1                1   
deadlock                                       0                0   
computer                                       1                0   

           USGS Precipitation-Runoff Modeling System.txt  TIBCO iProcess.txt  \
process                                                0                   1   
cpu                                                    0                   0   
operating                                              1                   1   
deadlock                                               0                   0   
computer                                               1                   0   

           Research Journal of Recent Sciences.txt  \
process                                          1   
cpu                                              0   
operating                                        1   
deadlock                                         1   
computer                                         1   

           Modern Operating Systems.txt  Operating Systems.txt  \
process                               1                      1   
cpu                                   0                      0   
operating                             0                      1   
deadlock                              1                      1   
computer                              0                      0   

           Topic- Operating Systems.txt  An Operating System1.txt  
process                               0                         1  
cpu                                   0                         0  
operating                             1                         1  
deadlock                              0                         0  
computer                              1                         1

# Part 4
Now, fetching the binary data of reqiured query terms

In [268]:
def query(kw):
  return df.loc[kw].values.flatten().tolist()

q1 = "process"
q2 = "cpu"
q3 = "deadlock"

In [269]:
query1 = np.array(query(q1))    
query2 = np.array(query(q2))
query3 = np.array(query(q3))

In [271]:
print(query1)
print(query2)
print(query3)

[1 1 1 1 0 1 1 1 1 0 1]
[0 1 1 0 0 0 0 0 0 0 0]
[1 1 0 0 0 0 1 1 1 0 0]


In [272]:
#query= q1 and q2 not q3

query=(query1 & query2 & ~query3)
print(query)

[0 0 1 0 0 0 0 0 0 0 0]


In [273]:
files=[]
for f in os.listdir():
  files.append(f)

In [274]:
result=[]

index=(np.where(query == 1)[0])

for i in index:
  result.append(files[i])

print(result)

['Operating Systems From 0 to 1.txt.txt']
